
alias a="atom ."
alias g="git"
alias gb="git branch"
alias gba="git branch -a"
alias gbaa="git for-each-ref --format='%(committerdate) %09 %(authorname) %09 %(refname)' | sort -k5n -k2M -k3n -k4n"
alias gc="git checkout"
alias gca="git commit -am"
alias gcm="git checkout master"
alias gcob="git checkout -b"
alias gfp="git fetch --prune"
alias gpl="git pull"
alias gplom="git pull origin master"
alias gpo="git push origin"
alias gpom="git push origin master"
alias gs="git status"

alias reload="source ~/.bash_profile"
alias ..="cd .."
alias turing="cd Documents/2016/Turing"
alias m3p="cd Documents/2016/Turing/mod-3/projects"
alias m4p="cd Documents/2016/Turing/mod-4/projects"
alias work="cd Documents/2017/Work/Code"

alias bashy="cd ; atom .bash_profile"
alias cls="printf '\033c'"

alias reinstall_node_modules="rm -rf node_modules && yarn install"
alias be="bundle exec"
alias berc="be rails c"
